[workspace]
authors = ["tdehoff <tatianadehoff@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "7-point-stencil"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.4.0.dev2025061205,<26"
